# Backbone
backbone: alexnet

# Optimizer related
lr: 0.01
weight_decay: 5e-4
momentum: 0.9
lr_scheduler: True
lr_gamma: 0.0003
lr_decay: 0.75

# Training related
batch_size: 128
n_iter_per_epoch: 20
n_epoch: 50

# Others
seed: 1
num_workers: 6